FROM node:20-bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm ci
COPY . .
RUN mkdir -p data
EXPOSE 3001
CMD ["npm", "run", "dev", "--", "--port", "3001"]